/// Flutter icons Shaarit
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shaarit
///      fonts:
///       - asset: fonts/Shaarit.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Shaarit {
  Shaarit._();

  static const _kFontFam = 'Shaarit';

  static const IconData logo_white = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData getcoupon = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData mycoupon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData shops = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData angel = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData icfilter = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData grgps = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData grid = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData grnotice = const IconData(0xe81c, fontFamily: _kFontFam);
}
